version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: ビルトイン環境変数
          command: |
            echo "CI is '$CI'" 
            echo "CIRCLE_SHA1 is '$CIRCLE_SHA1'" 
            echo "CIRCLE_BRANCH is '$CIRCLE_BRANCH'" 
          
workflows:
  version: 2
  build_and_test:
    jobs:
     - build:
          context: 
            - docker-hub-creds
